### ISSUE TITLE
running stuck seems to be it needs a lot of RAM memory

### ISSUE THREAD

**Issue by Sandy4321** [mktoid/MLBootCamp#1]
great code thanks
do you know other solutions?

for example, there is another one 
https://github.com/oalexandere/mlbootcamp_VI
what is the best results from 
https://mlbootcamp.ru/round/14/sandbox/#18

**Comment by mktoid** [comment]
Yes, this code was run at 128GB RAM virtual server.

It was possible to fit it into my laptop (12GB RAM) by splitting the dataset into 15 or 20 chunks like
`chunksize = 19528597 // 15 + 1`
and using train_test_split instead of KFold
as I did during development, 
though it gave a lower score.

The winning solution is described at https://habr.com/post/418743/
